hunter_config(OpenCV GIT_SUBMODULE "contrib/OpenCV"
  CMAKE_ARGS
  "BUILD_EXAMPLES=OFF
  BUILD_PERF_TESTS=OFF
  BUILD_TESTS=OFF
  BUILD_opencv_apps=OFF
  BUILD_opencv_python2=OFF
  BUILD_opencv_world=ON
  WITH_CUDA=OFF
  WITH_CUFFT=OFF
  WITH_GTK=OFF
  WITH_IPP=OFF
  WITH_IPP_A=OFF
  WITH_MATLAB=OFF
  WITH_QT=OFF")

hunter_config(Cinder GIT_SUBMODULE "contrib/Cinder"
  CMAKE_ARGS
  "CINDER_BOOST_USE_SYSTEM=ON
  CINDER_VERBOSE=ON")
